### ISSUE TITLE
pretrained model of FAQ

### ISSUE THREAD

**Issue by clk-ad** [YimingCuiCuiCui/FAQ#1]
Could pretrained model of FAQ be made public?

**Comment by HwaiHo-0552** [comment]
you can train by yourself.
To modify the code in  r50_train_single.sh could help you.

**Comment by HwaiHo-0552** [comment]
> Could pretrained model of FAQ be made public?
--------------------------------------------------------------------------
you can train by yourself.
To modify the code in r50_train_single.sh could help you.
